name: Install & setup
description: Install's node, pnpm, restores cache, and then installs dependencies

inputs:
  node-version:
    description: Node.js version to install
    default: '24'

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org
        cache: pnpm

    # Enable node compile cache (effective for Node 22+)
    # See https://nodejs.org/docs/v24.11.1/api/module.html#module-compile-cache
    - name: Enable Node Compile Cache
      shell: bash
      run: echo "NODE_COMPILE_CACHE=$HOME/.node_compile_cache" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
