import routingHandler from "@opennextjs/core/core/routingHandler.js";
import type { InternalEvent, RoutingResult } from "@opennextjs/core/types/open-next.js";
import { fromReadableStream, toReadableStream } from "@opennextjs/core/utils/stream.js";
import { vi } from "vitest";

vi.mock("@/config/index", () => ({
	BuildId: "build-id",
	NextConfig: {
		experimental: {},
		images: {},
		i18n: { locales: ["en", "fr"], defaultLocale: "en" },
	},
	RoutingConfig: {
		buildId: "build-id",
		pathnames: ["/en/foo", "/en/bar"],
		routeIndex: {
			"/en/foo": { type: "page", isFallback: false },
			"/en/bar": { type: "page", isFallback: false },
		},
		routes: {
			beforeMiddleware: [],
			beforeFiles: [],
			afterFiles: [],
			dynamicRoutes: [],
			onMatch: [],
			fallback: [],
			shouldNormalizeNextData: true,
		},
	},
	PrerenderManifest: { routes: {}, dynamicRoutes: {}, preview: {} },
	MiddlewareManifest: {
		middleware: {
			// Matcher generated by Next for `matcher: "/foo"` on an i18n app - see `getMiddlewareMatchers`.
			// The `_next/data` segment comes *before* the locale one.
			"/": {
				matchers: [
					{
						regexp: "^(?:/(_next/data/[^/]{1,}))?(?:/((?!_next/)[^/.]{1,}))/foo(?:\\.json)?[/#?]?$",
						originalSource: "/foo",
					},
				],
			},
		},
		functions: {},
		version: 3,
	},
	FunctionsConfigManifest: { functions: {}, version: 1 },
}));

const middleware = vi.fn().mockResolvedValue(
	new Response(null, {
		headers: { "x-middleware-next": "1" },
	})
);
const middlewareLoader = vi.fn().mockResolvedValue({ default: middleware });

function event(pathname: string): InternalEvent {
	return {
		type: "core",
		method: "GET",
		rawPath: pathname,
		url: `https://localhost${pathname}`,
		headers: { host: "localhost" },
		query: {},
		cookies: {},
		remoteAddress: "127.0.0.1",
	};
}

beforeEach(() => {
	globalThis.openNextConfig = {};
	vi.clearAllMocks();
});

describe("routingHandler middleware matching", () => {
	it("invokes the middleware for a matching page request", async () => {
		await routingHandler(event("/en/foo"), { middlewareLoader });

		expect(middlewareLoader).toHaveBeenCalled();
	});

	it("invokes the middleware for the `_next/data` request of a matching page", async () => {
		await routingHandler(event("/_next/data/build-id/en/foo.json"), { middlewareLoader });

		expect(middlewareLoader).toHaveBeenCalled();
		expect(middleware).toHaveBeenCalledWith(expect.objectContaining({ url: "https://localhost/en/foo" }));
	});

	it("forwards the request body after middleware reads it", async () => {
		middleware.mockImplementationOnce(async (request: { body?: InternalEvent["body"] }) => {
			expect(await fromReadableStream(request.body!)).toBe("request body");
			return new Response(null, { headers: { "x-middleware-next": "1" } });
		});
		const request = event("/en/foo");
		request.method = "POST";
		request.body = toReadableStream("request body");

		const result = (await routingHandler(request, { middlewareLoader })) as RoutingResult;

		expect(await fromReadableStream(result.internalEvent.body!)).toBe("request body");
	});

	it("forwards the request body when middleware runs before a 404", async () => {
		middleware.mockImplementationOnce(async (request: { body?: InternalEvent["body"] }) => {
			expect(await fromReadableStream(request.body!)).toBe("request body");
			return new Response(null, {
				headers: { "x-middleware-rewrite": "https://localhost/en/missing" },
			});
		});
		const request = event("/en/foo");
		request.method = "POST";
		request.body = toReadableStream("request body");

		const result = (await routingHandler(request, { middlewareLoader })) as RoutingResult;

		expect(result.internalEvent.rawPath).toBe("/404");
		expect(await fromReadableStream(result.internalEvent.body!)).toBe("request body");
	});

	it("does not invoke the middleware for a page the matchers exclude", async () => {
		await routingHandler(event("/en/bar"), { middlewareLoader });

		expect(middlewareLoader).not.toHaveBeenCalled();
	});

	it("does not invoke the middleware for the `_next/data` request of an excluded page", async () => {
		await routingHandler(event("/_next/data/build-id/en/bar.json"), { middlewareLoader });

		expect(middlewareLoader).not.toHaveBeenCalled();
	});
});
